const users = [
  {
    "leetcodeusername": "testuser1",
    "firstname": "John",
    "lastname": "Smith",
    "totalSolved": 360,
    "easySolved": 146,
    "mediumSolved": 196,
    "hardSolved": 21,
    "acceptanceRate": 50.92,
    "ranking": 47657,
  },
  {
    "leetcodeusername": "testuser2",
    "firstname": "Jane",
    "lastname": "Doe",
    "totalSolved": 270,
    "easySolved": 130,
    "mediumSolved": 130,
    "hardSolved": 10,
    "acceptanceRate": 56.7,
    "ranking": 67890,
  },
  {
    "leetcodeusername": "testuser3",
    "firstname": "Alex",
    "lastname": "Johnson",
    "totalSolved": 230,
    "easySolved": 100,
    "mediumSolved": 100,
    "hardSolved": 30,
    "acceptanceRate": 45.6,
    "ranking": 12345,
  },
  {
    "leetcodeusername": "testuser4",
    "firstname": "Liam",
    "lastname": "Williams",
    "totalSolved": 150,
    "easySolved": 80,
    "mediumSolved": 60,
    "hardSolved": 10,
    "acceptanceRate": 55.5,
    "ranking": 54321,
  },
  {
    "leetcodeusername": "testuser5",
    "firstname": "Emily",
    "lastname": "Jones",
    "totalSolved": 320,
    "easySolved": 140,
    "mediumSolved": 160,
    "hardSolved": 20,
    "acceptanceRate": 49.4,
    "ranking": 98765,
  },
  {
    "leetcodeusername": "testuser6",
    "firstname": "Noah",
    "lastname": "Miller",
    "totalSolved": 270,
    "easySolved": 120,
    "mediumSolved": 130,
    "hardSolved": 20,
    "acceptanceRate": 53.4,
    "ranking": 43210,
  },
  {
    "leetcodeusername": "testuser7",
    "firstname": "Ava",
    "lastname": "Davis",
    "totalSolved": 200,
    "easySolved": 90,
    "mediumSolved": 90,
    "hardSolved": 20,
    "acceptanceRate": 48.5,
    "ranking": 56789,
  },
  {
    "leetcodeusername": "testuser8",
    "firstname": "Isabella",
    "lastname": "Garcia",
    "totalSolved": 260,
    "easySolved": 110,
    "mediumSolved": 130,
    "hardSolved": 20,
    "acceptanceRate": 52.6,
    "ranking": 355,
  }];

module.exports = users;